variable "location" {}
variable "tre_id" {}
variable "ws_resource_group_name" {}
variable "enable_local_debugging" {}
variable "services_subnet_id" {}
variable "airlock_processor_subnet_id" {}
variable "workspace_unique_identifier_suffix" {}
variable "tre_workspace_tags" {}
variable "storage_account_name_suffix" {}
variable "workspace_resource_name_suffix" {}
